---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui 
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui 
  labels:
    app.kubernetes.io/name: open-webui 
spec:
  ports:
    - port: 8080 
      targetPort: 8080 
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: open-webui 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui 
  labels:
    app.kubernetes.io/name: open-webui 
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: open-webui 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-webui 
    spec:
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      containers:
        - name: open-webui 
          image: ghcr.io/open-webui/open-webui:main 
          env:
            - name: OLLAMA_BASE_URL
              value: http://ollama.ollama.svc.cluster.local:11434 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/backend/data 
      volumes:
        - name: data
          hostPath:
           path: /ssd/k3s/open-webui/data
           type: Directory

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui 
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - secretName: ai-sindt-org-tls
      hosts:
        - ai.sindt.org
  rules:
  - host: ai.sindt.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui 
            port:
              number: 8080 

